[processes.sleep]
cmd = "/bin/sleep"
args = ["3"]
processes = 40
umask = "022"
workingdir = "/tmp"
autostart = true
autorestart = "on-failure[:5]"
exitcodes = [0, 2]
stopsignals = ["TERM", "USR1"]
stoptime = 5
stdout = "/tmp/ls.stdout"
stderr = "/tmp/ls.stderr"
env = [["STARTED_BY", "abied-ch"], ["ANSWER", "42"]]
